#include <RTC.idl>
enum HB {
	ZERO,
	ONE
};

enum HBDone {
	UNDONE,
	DONE
};

interface HeartBeatService
{
	RTC::ReturnCode_t setOperatorToComp(in HB hbs);
	HB getOperatorToComp();
	RTC::ReturnCode_t setCompToOperator(in HB hbs);
	HB getCompToOperator();
	HBDone checkDone();
	void    setDone();
};